{% set name = "robotframework-browser" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43691e645059ef5bf1878794782abfb615effc9a63fe2c3588e780c575d85ac7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv && rfbrowser init
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - nodejs
    - backports.cached-property
    - grpcio
    - grpcio-tools
    - robotframework
    - robotframework-pythonlibcore
    - typing-extensions
    - wrapt
  run:
    - python
    - nodejs
    - backports.cached-property
    - grpcio
    - grpcio-tools
    - robotframework
    - robotframework-pythonlibcore
    - typing-extensions
    - wrapt

test:
  imports:
    - Browser

about:
  home: https://github.com/MarketSquare/robotframework-browser
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Robot Framework Browser library powered by Playwright.
  description: |
    Robot Framework Browser library powered by Playwright. Moving browser automation to year 2020 (or 2021)!
    Aiming for speed, reliability and visibility.
  doc_url: https://marketsquare.github.io/robotframework-browser/Browser.html
  dev_url: https://github.com/MarketSquare/robotframework-browser

extra:
  recipe-maintainers:
    - martinRenou
    - xylix
    - conda-forge/rpaframework-core
